import {
  Child,
  ClassScheduleItem,
  AcademicAssessment,
  PedagogicalMeeting,
  SchoolCircular,
  ExtracurricularActivity,
  SocialEvent,
  Medication,
  MedicationLog,
  VaccineRecord,
  MedicalAppointment,
  GrowthRecord,
  Note,
  Task,
  MemoryMoment,
  DevelopmentMilestone,
  ArtworkItem,
  DocumentFile,
} from '../types';

export const INITIAL_CHILDREN: Child[] = [
  {
    id: 'helena',
    name: 'Helena',
    birthDate: '2019-06-14',
    age: '7 anos',
    schoolName: 'Colégio Santa Teresa',
    grade: '2º Ano Fundamental',
    avatarColor: 'bg-warm-peach/60 text-warm-terracotta-dark',
    accentColor: 'border-warm-peach',
    initials: 'H',
    themeBadge: 'badge-peach',
    bloodType: 'A +',
    allergies: [
      'Amendoim & Frutas Oleaginosas (Grave - Anafilaxia)',
      'Penicilina & Derivados',
      'Sensibilidade a picada de abelha',
    ],
    pediatricianName: 'Dra. Beatriz Albuquerque',
    pediatricianPhone: '(11) 99988-7766',
    pediatricianCrm: 'CRM 142.890-SP',
    referenceHospital: 'Hospital Infantil Sabará',
    referenceHospitalPhone: '(11) 3155-2800',
    healthInsurance: 'SulAmérica Especial (Carteirinha: 849204-01)',
  },
  {
    id: 'mateo',
    name: 'Mateo',
    birthDate: '2022-03-22',
    age: '4 anos',
    schoolName: 'Escola Espaço Criativo',
    grade: 'Jardim II',
    avatarColor: 'bg-calm-sage/30 text-calm-sage-dark',
    accentColor: 'border-calm-sage',
    initials: 'M',
    themeBadge: 'badge-sage',
    bloodType: 'O +',
    allergies: ['Intolerância transitória à lactose'],
    pediatricianName: 'Dr. Fernando Vasconcelos',
    pediatricianPhone: '(11) 98877-6655',
    pediatricianCrm: 'CRM 115.430-SP',
    referenceHospital: 'Hospital Infantil Sabará',
    referenceHospitalPhone: '(11) 3155-2800',
    healthInsurance: 'SulAmérica Especial (Carteirinha: 849204-02)',
  },
];

export const INITIAL_SCHEDULE: ClassScheduleItem[] = [
  {
    id: 'sch-1',
    childId: 'helena',
    dayOfWeek: 'Quinta',
    subject: 'Matemática Lúdica & Geometria',
    startTime: '08:00',
    endTime: '08:50',
    duration: '50 min',
    teacher: 'Profª. Camila Rodrigues',
    room: 'Sala 14B',
    colorTag: 'badge-slate',
    materials: [
      { id: 'm-1', name: 'Caderno de pauta quadriculada', checked: true },
      { id: 'm-2', name: 'Régua de 20cm e estojo de lápis', checked: true },
    ],
  },
  {
    id: 'sch-2',
    childId: 'helena',
    dayOfWeek: 'Quinta',
    subject: 'Língua Portuguesa & Leitura Viva',
    startTime: '09:00',
    endTime: '10:00',
    duration: '60 min',
    teacher: 'Profª. Helena Fontes',
    room: 'Biblioteca Central',
    colorTag: 'badge-peach',
    materials: [
      { id: 'm-3', name: 'Livro de histórias infantis', checked: false },
      { id: 'm-4', name: 'Caderno de caligrafia', checked: true },
    ],
  },
  {
    id: 'sch-3',
    childId: 'helena',
    dayOfWeek: 'Quinta',
    subject: 'Educação Artística & Pintura em Aquarela',
    startTime: '10:30',
    endTime: '11:45',
    duration: '75 min',
    teacher: 'Profª. Marcela Diniz',
    room: 'Ateliê das Cores',
    colorTag: 'badge-sage',
    materials: [
      { id: 'm-5', name: 'Avental impermeável de pintura', checked: false },
      { id: 'm-6', name: 'Pincel chanfrado nº 8', checked: true },
    ],
  },
  {
    id: 'sch-4',
    childId: 'mateo',
    dayOfWeek: 'Quinta',
    subject: 'Psicomotricidade & Jogos Coletivos',
    startTime: '08:30',
    endTime: '09:45',
    duration: '75 min',
    teacher: 'Tio Lucas',
    room: 'Pátio Coberto',
    colorTag: 'badge-sage',
    materials: [
      { id: 'm-7', name: 'Tênis com velcro para correr', checked: true },
      { id: 'm-8', name: 'Garrafinha de água', checked: true },
    ],
  },
  {
    id: 'sch-5',
    childId: 'mateo',
    dayOfWeek: 'Quinta',
    subject: 'Contação de Histórias & Fantoches',
    startTime: '10:15',
    endTime: '11:30',
    duration: '75 min',
    teacher: 'Tia Júlia',
    room: 'Sala de Tapete',
    colorTag: 'badge-peach',
    materials: [
      { id: 'm-9', name: 'Almofadinha de descanso', checked: true },
    ],
  },
];

export const INITIAL_ASSESSMENTS: AcademicAssessment[] = [
  {
    id: 'ass-1',
    childId: 'helena',
    subject: 'Matemática',
    title: 'Avaliação Bimestral de Operações e Formas',
    type: 'Prova',
    date: '28 de Setembro',
    weight: 4.0,
    grade: 9.5,
    classAverage: 8.2,
    status: 'Avaliado',
    notes: 'Excelente raciocínio lógico e organização das contas.',
  },
  {
    id: 'ass-2',
    childId: 'helena',
    subject: 'Ciências & Natureza',
    title: 'Projeto do Ciclo da Água e Terrário',
    type: 'Feira de Ciências',
    date: '05 de Outubro',
    weight: 3.0,
    status: 'Agendado',
    notes: 'Apresentação em grupo de 3 crianças no auditório.',
  },
  {
    id: 'ass-3',
    childId: 'helena',
    subject: 'Língua Portuguesa',
    title: 'Redação Narrativa: Minhas Férias Inesquecíveis',
    type: 'Trabalho',
    date: '15 de Setembro',
    weight: 3.0,
    grade: 10.0,
    classAverage: 8.6,
    status: 'Avaliado',
    notes: 'Criatividade impecável e vocabulário expressivo.',
  },
];

export const INITIAL_MEETINGS: PedagogicalMeeting[] = [
  {
    id: 'meet-1',
    childId: 'helena',
    date: '10 de Setembro de 2026',
    teacherOrCoordinator: 'Profª. Camila Rodrigues & Coord. Alice',
    topics: ['Socialização em grupo', 'Foco na leitura autônoma', 'Expressão artística'],
    feedbacks: 'Helena é extremamente solícita com os colegas. Tem demonstrado liderança positiva nas rodas de conversa e uma curiosidade aguçada por livros.',
    actionPoints: [
      'Incentivar a leitura de livros com capítulos curtos em casa.',
      'Reforçar o uso de relógio para ajudar na gestão do tempo das lições.',
    ],
  },
];

export const INITIAL_CIRCULARS: SchoolCircular[] = [
  {
    id: 'circ-1',
    childId: 'helena',
    title: 'Comunicado nº 18: Feira Literária e Semana da Criança',
    category: 'Circular',
    date: '12/Set/2026',
    description: 'Programação oficial da Semana Literária, autores convidados e oficinas infantis.',
    fileSize: '1.4 MB',
  },
  {
    id: 'circ-2',
    childId: 'helena',
    title: 'Calendário Oficial do Ano Letivo 2026/2027',
    category: 'Calendário Oficial',
    date: '01/Fev/2026',
    description: 'Datas de recessos, semanas de provas, reuniões de pais e encerramento.',
    fileSize: '3.1 MB',
  },
];

export const INITIAL_ACTIVITIES: ExtracurricularActivity[] = [
  {
    id: 'act-1',
    childId: 'helena',
    title: 'Ballet Clássico Infantil',
    category: 'Artes',
    daysOfWeek: ['Terça', 'Quinta'],
    startTime: '15:00',
    endTime: '16:00',
    instructorName: 'Profª. Laura Meirelles',
    instructorContact: '(11) 97766-5544',
    institution: 'Academia Corpo & Movimento',
    address: 'Alameda dos Ipês, 450 - Jardins',
    routeUrl: 'https://maps.google.com',
    equipmentChecklist: ['Collant rosa bebê', 'Sapatilhas de meia-ponta', 'Redinha de coque'],
    badgeColor: 'badge-peach',
  },
  {
    id: 'act-2',
    childId: 'helena',
    title: 'Inglês Lúdico & Imersão',
    category: 'Idiomas',
    daysOfWeek: ['Segunda', 'Quarta'],
    startTime: '14:30',
    endTime: '15:45',
    instructorName: 'Teacher Mark Davis',
    instructorContact: '(11) 98899-1122',
    institution: 'Little Explorers Language Institute',
    address: 'Rua Bela Cintra, 1200 - Consolação',
    equipmentChecklist: ['Pasta de atividades', 'Fones de ouvido infantis'],
    badgeColor: 'badge-slate',
  },
  {
    id: 'act-3',
    childId: 'mateo',
    title: 'Natação e Adaptação Aquática',
    category: 'Esporte',
    daysOfWeek: ['Quarta', 'Sexta'],
    startTime: '16:00',
    endTime: '16:45',
    instructorName: 'Prof. Gustavo Prado',
    instructorContact: '(11) 99123-4567',
    institution: 'Clube Aquático Golfinhos',
    address: 'Av. Paulista, 2200',
    equipmentChecklist: ['Sunga térmica', 'Óculos de natação', 'Roupão felpudo e toalha'],
    badgeColor: 'badge-sage',
  },
];

export const INITIAL_SOCIAL_EVENTS: SocialEvent[] = [
  {
    id: 'soc-1',
    childId: 'helena',
    title: 'Aniversário de 7 anos da Beatriz (Colega de Sala)',
    eventType: 'Aniversário',
    date: '27 de Setembro às 16h',
    time: '16:00 - 20:00',
    location: 'Buffet Infantil Cata-Vento (Vila Olímpia)',
    giftSuggestion: 'Livros de quebra-cabeça ou kit de massinhas',
    confirmed: true,
    notes: 'Levar fantasia de princesa solicitada no convite.',
  },
  {
    id: 'soc-2',
    childId: 'mateo',
    title: 'Piquenique da Turminha do Jardim',
    eventType: 'Passeio',
    date: '04 de Outubro às 10h',
    time: '10:00 - 13:00',
    location: 'Parque Ibirapuera (Portão 7)',
    giftSuggestion: 'Fruta fresca lavada para compartilhar',
    confirmed: true,
  },
];

export const INITIAL_MEDICATIONS: Medication[] = [
  {
    id: 'med-1',
    childId: 'helena',
    name: 'Amoxicilina + Clavulanato (Suspensão)',
    dosage: '5.0 ml',
    intervalHours: 8,
    startDate: '16/Set/2026',
    endDate: '23/Set/2026',
    isActive: true,
    instructions: 'Administrar sempre após as refeições. Agitar bem antes de usar.',
    nextDoseTime: '23:30',
  },
  {
    id: 'med-2',
    childId: 'helena',
    name: 'Vitamina D3 em Gotas',
    dosage: '2 gotas ao dia',
    intervalHours: 24,
    startDate: '01/Jan/2026',
    endDate: '31/Dez/2026',
    isActive: true,
    instructions: 'Uso contínuo matinal no suco de laranja.',
    nextDoseTime: '08:00 (Amanhã)',
  },
  {
    id: 'med-3',
    childId: 'mateo',
    name: 'Lavagem Nasal com Soro Fisiológico 0.9%',
    dosage: '5 ml em cada narina',
    intervalHours: 12,
    startDate: '01/Set/2026',
    endDate: '30/Set/2026',
    isActive: true,
    instructions: 'Ao acordar e antes de dormir para alívio respiratório.',
    nextDoseTime: '20:30',
  },
];

export const INITIAL_MED_LOGS: MedicationLog[] = [
  {
    id: 'log-1',
    medicationId: 'med-1',
    childId: 'helena',
    medicationName: 'Amoxicilina (5.0 ml)',
    caregiver: 'Mamãe (Mariana)',
    administeredAt: 'Hoje às 07:30',
    note: 'Tomou bem com o café da manhã.',
  },
  {
    id: 'log-2',
    medicationId: 'med-1',
    childId: 'helena',
    medicationName: 'Amoxicilina (5.0 ml)',
    caregiver: 'Papai (Rodrigo)',
    administeredAt: 'Hoje às 15:30',
    note: 'Dose da tarde sem nenhuma queixa.',
  },
];

export const INITIAL_VACCINES: VaccineRecord[] = [
  {
    id: 'vac-1',
    childId: 'helena',
    vaccineName: 'Tríplice Viral (Sarampo, Caxumba, Rubéola)',
    dose: 'Dose de Reforço (4 a 6 anos)',
    recommendedAge: '5 anos',
    applicationDate: '15/06/2024',
    status: 'Aplicada',
    batchLocation: 'UBS Pinheiros - Lote TR4920',
  },
  {
    id: 'vac-2',
    childId: 'helena',
    vaccineName: 'Febre Amarela',
    dose: 'Reforço aos 4 anos',
    recommendedAge: '4 anos',
    applicationDate: '10/07/2023',
    status: 'Aplicada',
    batchLocation: 'Clínica Pro Vacinas',
  },
  {
    id: 'vac-3',
    childId: 'helena',
    vaccineName: 'HPV Quadrivalente',
    dose: '1ª Dose',
    recommendedAge: '9 anos',
    status: 'Pendente',
  },
  {
    id: 'vac-4',
    childId: 'mateo',
    vaccineName: 'DTP (Difteria, Tétano, Coqueluche)',
    dose: '2º Reforço',
    recommendedAge: '4 anos',
    applicationDate: '25/04/2026',
    status: 'Aplicada',
    batchLocation: 'UBS Jardim Paulista',
  },
  {
    id: 'vac-5',
    childId: 'mateo',
    vaccineName: 'Varicela (Catapora)',
    dose: '2ª Dose',
    recommendedAge: '4 anos',
    status: 'Pendente',
  },
];

export const INITIAL_APPOINTMENTS: MedicalAppointment[] = [
  {
    id: 'app-1',
    childId: 'helena',
    specialty: 'Pediatria de Rotina & Puericultura',
    doctorName: 'Dra. Beatriz Albuquerque',
    clinic: 'Consultório Integrado de Pediatria',
    date: '18 de Agosto de 2026',
    time: '14:30',
    symptoms: 'Check-up semestral de desenvolvimento escolar e peso.',
    diagnosis: 'Crescimento e peso harmoniosos no percentil 65. Visão e audição sem queixas.',
    prescriptions: ['Manter Vitamina D3', 'Retorno semestral em Fevereiro/2027'],
    returnDate: '18/02/2027',
  },
  {
    id: 'app-2',
    childId: 'helena',
    specialty: 'Oftalmologia Pediátrica',
    doctorName: 'Dr. Roberto Silveira',
    clinic: 'Instituto de Olhos SP',
    date: '10 de Julho de 2026',
    time: '10:00',
    diagnosis: 'Acuidade visual 20/20 bilateral. Sem necessidade de correção óptica.',
    prescriptions: ['Proteger olhos da radiação solar em praia/parque'],
    returnDate: '10/07/2027',
  },
];

export const INITIAL_GROWTH: GrowthRecord[] = [
  {
    id: 'gr-1',
    childId: 'helena',
    date: '18/Set/2026',
    ageMonths: 87,
    ageDisplay: '7 anos e 3 meses',
    heightCm: 122.5,
    weightKg: 24.2,
    headCircumferenceCm: 51.5,
    percentileText: 'Percentil 65 (Evolução Ideal OMS)',
    notes: 'Ganho estável de estatura. Disposição e apetite normais.',
  },
  {
    id: 'gr-2',
    childId: 'helena',
    date: '15/Mar/2026',
    ageMonths: 81,
    ageDisplay: '6 anos e 9 meses',
    heightCm: 118.0,
    weightKg: 22.8,
    percentileText: 'Percentil 62',
  },
  {
    id: 'gr-3',
    childId: 'helena',
    date: '10/Set/2025',
    ageMonths: 75,
    ageDisplay: '6 anos e 3 meses',
    heightCm: 114.5,
    weightKg: 21.3,
    percentileText: 'Percentil 60',
  },
  {
    id: 'gr-4',
    childId: 'mateo',
    date: '12/Set/2026',
    ageMonths: 54,
    ageDisplay: '4 anos e 6 meses',
    heightCm: 105.0,
    weightKg: 17.4,
    percentileText: 'Percentil 70',
    notes: 'Desenvolvimento motor excelente.',
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: 'note-1',
    childId: 'helena',
    title: 'Acordo sobre o tempo de telas durante a semana',
    content: 'Combinamos que de segunda a quinta não haverá tablet antes das 18h e sempre após a lição de casa terminada. Helena sugeriu que aos sábados ela possa ajudar no bolo como comemoração pelo cumprimento da regra.',
    tags: ['#comportamento', '#combinados'],
    isPinned: true,
    createdAt: '18 de Setembro às 20h30',
    tagColorClass: 'badge-peach',
  },
  {
    id: 'note-2',
    childId: 'helena',
    title: 'Orientações da psicopedagoga para incentivar a leitura autônoma',
    content: 'Fazer pausas dramáticas ao ler juntos e perguntar: "O que você acha que vai acontecer na próxima página?". Isso desenvolve raciocínio preditivo e imaginação.',
    tags: ['#escola', '#pedagogia'],
    isPinned: false,
    createdAt: '14 de Setembro às 11h15',
    tagColorClass: 'badge-slate',
  },
  {
    id: 'note-3',
    childId: 'mateo',
    title: 'Ideias de brincadeiras sensoriais para o fim de semana',
    content: 'Massinha caseira de farinha com corante de beterraba e espinafre. Ajuda na coordenação motora fina e segurança caso ele coloque na boca.',
    tags: ['#ideias', '#brincadeiras'],
    isPinned: true,
    createdAt: '12 de Setembro às 16h40',
    tagColorClass: 'badge-sage',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-1',
    childId: 'helena',
    title: 'Arrumar a caminha e guardar o pijaminha',
    category: 'child',
    priority: 'media',
    dueTime: 'Manhã',
    completed: true,
    rewardStars: 2,
  },
  {
    id: 'tsk-2',
    childId: 'helena',
    title: 'Regar os vasinhos de tempero na varanda',
    category: 'child',
    priority: 'baixa',
    dueTime: 'Tarde (16h)',
    completed: false,
    rewardStars: 1,
  },
  {
    id: 'tsk-3',
    childId: 'helena',
    title: 'Guardar os materiais de pintura na caixa do ateliê',
    category: 'child',
    priority: 'alta',
    dueTime: 'Noite (19h)',
    completed: false,
    rewardStars: 3,
  },
  {
    id: 'tsk-4',
    childId: 'helena',
    title: 'Assinar e devolver autorização do passeio pedagógico',
    category: 'parent',
    priority: 'alta',
    dueTime: 'Hoje até 18h',
    completed: true,
  },
  {
    id: 'tsk-5',
    childId: 'helena',
    title: 'Comprar a cartolina holográfica para a Feira de Ciências',
    category: 'parent',
    priority: 'media',
    dueTime: 'Amanhã',
    completed: false,
  },
  {
    id: 'tsk-6',
    childId: 'mateo',
    title: 'Guardar os blocos de montar no cesto de brinquedos',
    category: 'child',
    priority: 'media',
    dueTime: 'Antes do jantar',
    completed: false,
    rewardStars: 2,
  },
];

export const INITIAL_MEMORIES: MemoryMoment[] = [
  {
    id: 'mem-1',
    childId: 'helena',
    title: 'Primeira Apresentação de Balé no Teatro Municipal',
    date: '12 de Setembro de 2026',
    narrative: 'Helena estava com frio na barriga antes de subir ao palco. Quando a cortina abriu e a valsa começou, ela deu o sorriso mais doce do mundo. Guardamos as sapatilhas autografadas por ela.',
    category: 'Conquistas',
    location: 'Teatro Municipal de SP',
  },
  {
    id: 'mem-2',
    childId: 'helena',
    title: 'Dia em que leu a primeira história inteira em voz alta',
    date: '28 de Agosto de 2026',
    narrative: 'Sentamos na rede da varanda no fim da tarde. Ela abriu "O Menino e o Vento" e leu 12 páginas sem pedir ajuda. Seus olhinhos brilhavam de orgulho.',
    category: 'Escola',
    location: 'Varanda de Casa',
  },
  {
    id: 'mem-3',
    childId: 'mateo',
    title: 'Primeira vez mergulhando sem boia de braço',
    date: '05 de Setembro de 2026',
    narrative: 'Mateo pulou na piscina rasa direto no colo do pai rindo alto e pedindo "de novo, de novo!". Uma conquista linda de coragem.',
    category: 'Férias',
    location: 'Clube Aquático',
  },
];

export const INITIAL_MILESTONES: DevelopmentMilestone[] = [
  {
    id: 'mil-1',
    childId: 'helena',
    title: 'Leitura Autônoma de Livros de História',
    category: 'Linguagem',
    ageAchieved: '7 anos e 2 meses',
    dateAchieved: 'Agosto/2026',
    description: 'Decodificação fluida, interpretação de personagens e entusiasmo com a literatura infantil.',
  },
  {
    id: 'mil-2',
    childId: 'helena',
    title: 'Primeira Troca de Dente de Leite',
    category: 'Motor',
    ageAchieved: '6 anos e 1 mês',
    dateAchieved: 'Julho/2025',
    description: 'Incisivo central inferior caiu comendo maçã. Deixou a cartinha para a Fada do Dente.',
  },
  {
    id: 'mil-3',
    childId: 'mateo',
    title: 'Expressão de Frases Complexas com "Por quê?"',
    category: 'Linguagem',
    ageAchieved: '3 anos e 8 meses',
    dateAchieved: 'Novembro/2025',
    description: 'Início da fase das perguntas investigativas e curiosidade pelo mundo.',
  },
];

export const INITIAL_ARTWORKS: ArtworkItem[] = [
  {
    id: 'art-1',
    childId: 'helena',
    title: 'O Jardim Secreto dos Pássaros Amarelos',
    date: '08 de Setembro de 2026',
    technique: 'Aquarela & Giz Pastel sobre Papel Canson 300g',
    description: 'Criado durante a aula de artes da escola. Ela disse que os pássaros estavam cantando para acordar as flores.',
  },
  {
    id: 'art-2',
    childId: 'mateo',
    title: 'O Dinossauro Azul e a Chuva de Estrelas',
    date: '02 de Setembro de 2026',
    technique: 'Tinta Guache com Pintura a Dedo',
    description: 'Pintura livre cheia de energia e cores vivas no cavalete de casa.',
  },
];

export const INITIAL_DOCUMENTS: DocumentFile[] = [
  {
    id: 'doc-1',
    childId: 'helena',
    name: 'Certidao_Nascimento_Helena_Oficial.pdf',
    folderCategory: 'Oficiais',
    fileType: 'pdf',
    size: '1.8 MB',
    uploadDate: '15/Jan/2026',
    description: 'Certidão autenticada com firma digital.',
  },
  {
    id: 'doc-2',
    childId: 'helena',
    name: 'Carteira_Vacinacao_Atualizada_2026.pdf',
    folderCategory: 'Saúde',
    fileType: 'pdf',
    size: '2.4 MB',
    uploadDate: '10/Set/2026',
    description: 'Registro completo de vacinas aplicadas e carimbadas pela UBS.',
  },
  {
    id: 'doc-3',
    childId: 'helena',
    name: 'Boletim_Escolar_2ºBimestre_2026.pdf',
    folderCategory: 'Educação',
    fileType: 'pdf',
    size: '890 KB',
    uploadDate: '02/Set/2026',
    description: 'Boletim assinado pela coordenação pedagógica.',
  },
  {
    id: 'doc-4',
    childId: 'helena',
    name: 'RG_Helena_FrenteVerso_Digitalizado.jpg',
    folderCategory: 'Oficiais',
    fileType: 'image',
    size: '3.1 MB',
    uploadDate: '20/Jul/2026',
    description: 'Cópia nítida do documento de identidade emitido pelo Poupatempo.',
  },
  {
    id: 'doc-5',
    childId: 'mateo',
    name: 'Certidao_Nascimento_Mateo.pdf',
    folderCategory: 'Oficiais',
    fileType: 'pdf',
    size: '1.6 MB',
    uploadDate: '15/Jan/2026',
  },
  {
    id: 'doc-6',
    childId: 'mateo',
    name: 'Exame_Audiometria_Mateo_2026.pdf',
    folderCategory: 'Saúde',
    fileType: 'pdf',
    size: '1.1 MB',
    uploadDate: '14/Ago/2026',
  },
];
