import {
  Child,
  ClassScheduleItem,
  AcademicAssessment,
  PedagogicalMeeting,
  SchoolCircular,
  ExtracurricularActivity,
  SocialEvent,
  Medication,
  MedicalPrescription,
  MedicationLog,
  VaccineRecord,
  MedicalAppointment,
  GrowthRecord,
  Note,
  Task,
  MemoryMoment,
  DevelopmentMilestone,
  ArtworkItem,
  DocumentFile,
} from '../types';

export const INITIAL_CHILDREN: Child[] = [
  {
    id: 'helena',
    name: 'Helena',
    birthDate: '2019-06-14',
    age: '7 anos',
    schoolName: 'Colégio Santa Teresa',
    grade: '2º Ano Fundamental',
    avatarColor: 'bg-warm-peach/60 text-warm-terracotta-dark',
    accentColor: 'border-warm-peach',
    initials: 'H',
    themeBadge: 'badge-peach',
    bloodType: 'A +',
    allergies: [
      'Amendoim & Frutas Oleaginosas (Grave - Anafilaxia)',
      'Penicilina & Derivados',
      'Sensibilidade a picada de abelha',
    ],
    pediatricianName: 'Dra. Beatriz Albuquerque',
    pediatricianPhone: '(11) 99988-7766',
    pediatricianCrm: 'CRM 142.890-SP',
    referenceHospital: 'Hospital Infantil Sabará',
    referenceHospitalPhone: '(11) 3155-2800',
    healthInsurance: 'SulAmérica Especial (Carteirinha: 849204-01)',
  },
  {
    id: 'mateo',
    name: 'Mateo',
    birthDate: '2022-03-22',
    age: '4 anos',
    schoolName: 'Escola Espaço Criativo',
    grade: 'Jardim II',
    avatarColor: 'bg-calm-sage/30 text-calm-sage-dark',
    accentColor: 'border-calm-sage',
    initials: 'M',
    themeBadge: 'badge-sage',
    bloodType: 'O +',
    allergies: ['Intolerância transitória à lactose'],
    pediatricianName: 'Dr. Fernando Vasconcelos',
    pediatricianPhone: '(11) 98877-6655',
    pediatricianCrm: 'CRM 115.430-SP',
    referenceHospital: 'Hospital Infantil Sabará',
    referenceHospitalPhone: '(11) 3155-2800',
    healthInsurance: 'SulAmérica Especial (Carteirinha: 849204-02)',
  },
  {
    id: 'laura',
    name: 'Laura',
    birthDate: '2014-08-10',
    age: '12 anos',
    schoolName: 'Colégio Santa Teresa',
    grade: '7º Ano do Ensino Fundamental',
    avatarColor: 'bg-warm-terracotta/20 text-warm-terracotta-dark',
    accentColor: 'border-warm-terracotta',
    initials: 'L',
    themeBadge: 'badge-terracotta',
    bloodType: 'B +',
    allergies: ['Frutos do mar (camarão)', 'Rinite alérgica a ácaros e poeira'],
    pediatricianName: 'Dra. Mariana Gontijo (Hebiatra)',
    pediatricianPhone: '(11) 98765-4321',
    pediatricianCrm: 'CRM 168.902-SP',
    referenceHospital: 'Hospital Sírio-Libanês Infantil',
    referenceHospitalPhone: '(11) 3394-0200',
    healthInsurance: 'SulAmérica Especial (Carteirinha: 849204-03)',
  },
  {
    id: 'lucas',
    name: 'Lucas',
    birthDate: '2024-02-18',
    age: '2 anos',
    schoolName: 'Berçário Primeiros Passos',
    grade: 'Maternal I',
    avatarColor: 'bg-amber-100 text-amber-900',
    accentColor: 'border-amber-300',
    initials: 'Lu',
    themeBadge: 'badge-amber',
    bloodType: 'A +',
    allergies: ['Dermatite atópica leve (usar sabonetes hipoalergênicos)'],
    pediatricianName: 'Dr. Fernando Vasconcelos',
    pediatricianPhone: '(11) 98877-6655',
    pediatricianCrm: 'CRM 115.430-SP',
    referenceHospital: 'Hospital Infantil Sabará',
    referenceHospitalPhone: '(11) 3155-2800',
    healthInsurance: 'SulAmérica Especial (Carteirinha: 849204-04)',
  },
];

export const INITIAL_SCHEDULE: ClassScheduleItem[] = [
  // Helena (7 anos)
  {
    id: 'sch-1',
    childId: 'helena',
    dayOfWeek: 'Quinta',
    subject: 'Matemática Lúdica & Geometria',
    startTime: '08:00',
    endTime: '08:50',
    duration: '50 min',
    teacher: 'Profª. Camila Rodrigues',
    room: 'Sala 14B',
    colorTag: 'badge-slate',
    materials: [
      { id: 'm-1', name: 'Caderno de pauta quadriculada', checked: true },
      { id: 'm-2', name: 'Régua de 20cm e estojo de lápis', checked: true },
    ],
  },
  {
    id: 'sch-2',
    childId: 'helena',
    dayOfWeek: 'Quinta',
    subject: 'Língua Portuguesa & Leitura Viva',
    startTime: '09:00',
    endTime: '10:00',
    duration: '60 min',
    teacher: 'Profª. Helena Fontes',
    room: 'Biblioteca Central',
    colorTag: 'badge-peach',
    materials: [
      { id: 'm-3', name: 'Livro de histórias infantis', checked: false },
      { id: 'm-4', name: 'Caderno de caligrafia', checked: true },
    ],
  },
  {
    id: 'sch-3',
    childId: 'helena',
    dayOfWeek: 'Sexta',
    subject: 'Ciências da Natureza & Horta Escolar',
    startTime: '10:30',
    endTime: '11:40',
    duration: '70 min',
    teacher: 'Prof. André Queiroz',
    room: 'Laboratório & Estufa',
    colorTag: 'badge-sage',
    materials: [
      { id: 'm-5', name: 'Avental de jardinagem', checked: true },
      { id: 'm-6', name: 'Lupa e caderno de anotações de campo', checked: false },
    ],
  },
  // Mateo (4 anos)
  {
    id: 'sch-4',
    childId: 'mateo',
    dayOfWeek: 'Quinta',
    subject: 'Oficina de Expressão & Pintura com Dedos',
    startTime: '08:30',
    endTime: '09:30',
    duration: '60 min',
    teacher: 'Tia Juliana',
    room: 'Ateliê Infantil',
    colorTag: 'badge-peach',
    materials: [
      { id: 'm-7', name: 'Avental plástico impermeável', checked: true },
      { id: 'm-8', name: 'Toalhinha de mão com nome bordado', checked: true },
      { id: 'm-9', name: 'Garrafinha térmica de água', checked: true },
    ],
  },
  {
    id: 'sch-5',
    childId: 'mateo',
    dayOfWeek: 'Quinta',
    subject: 'Roda de Contação de Histórias & Fantoches',
    startTime: '10:00',
    endTime: '11:00',
    duration: '60 min',
    teacher: 'Tio Marcelo',
    room: 'Toca dos Sonhos',
    colorTag: 'badge-sage',
    materials: [
      { id: 'm-10', name: 'Meias antiderrapantes', checked: true },
      { id: 'm-11', name: 'Mochila com muda de roupa reserva', checked: true },
    ],
  },
  // Laura (12 anos)
  {
    id: 'sch-6',
    childId: 'laura',
    dayOfWeek: 'Quinta',
    subject: 'Ciências & Biologia Celular',
    startTime: '07:30',
    endTime: '09:10',
    duration: '100 min',
    teacher: 'Prof. Marcos Vinícius',
    room: 'Lab de Biologia 02',
    colorTag: 'badge-sage',
    materials: [
      { id: 'm-12', name: 'Jaleco branco de algodão', checked: true },
      { id: 'm-13', name: 'Apostila de Biologia Módulo 3', checked: true },
      { id: 'm-14', name: 'Calculadora científica', checked: true },
    ],
  },
  {
    id: 'sch-7',
    childId: 'laura',
    dayOfWeek: 'Quinta',
    subject: 'História & Civilizações Antigas',
    startTime: '09:30',
    endTime: '11:10',
    duration: '100 min',
    teacher: 'Profª. Clarice Drummond',
    room: 'Sala 28 (Bloco C)',
    colorTag: 'badge-terracotta',
    materials: [
      { id: 'm-15', name: 'Livro de História Geral', checked: true },
      { id: 'm-16', name: 'Caderno universitário 10 matérias', checked: true },
    ],
  },
  // Lucas (2 anos)
  {
    id: 'sch-8',
    childId: 'lucas',
    dayOfWeek: 'Quinta',
    subject: 'Exploração Sensorial & Parquinho de Areia',
    startTime: '09:00',
    endTime: '10:15',
    duration: '75 min',
    teacher: 'Educadora Renata',
    room: 'Solário & Playground Baby',
    colorTag: 'badge-amber',
    materials: [
      { id: 'm-17', name: 'Protetor solar mineral infantil', checked: true },
      { id: 'm-18', name: 'Chapéu com proteção UV', checked: true },
      { id: 'm-19', name: '2 mudas de roupas completas', checked: true },
      { id: 'm-20', name: 'Fraldas e pomada de barreira', checked: true },
    ],
  },
];

export const INITIAL_ASSESSMENTS: AcademicAssessment[] = [
  // Helena
  {
    id: 'ass-1',
    childId: 'helena',
    subject: 'Matemática',
    title: 'Avaliação Bimestral de Operações e Formas',
    type: 'Prova',
    date: '28 de Setembro',
    weight: 4.0,
    grade: 9.5,
    classAverage: 8.2,
    status: 'Avaliado',
    notes: 'Excelente raciocínio lógico e organização das contas.',
  },
  {
    id: 'ass-2',
    childId: 'helena',
    subject: 'Ciências & Natureza',
    title: 'Projeto do Ciclo da Água e Terrário',
    type: 'Feira de Ciências',
    date: '05 de Outubro',
    weight: 3.0,
    status: 'Agendado',
    notes: 'Apresentação em grupo de 3 crianças no auditório.',
  },
  // Laura
  {
    id: 'ass-3',
    childId: 'laura',
    subject: 'Matemática & Álgebra',
    title: 'Prova Bimestral de Equações de 1º Grau',
    type: 'Prova',
    date: '24 de Setembro',
    weight: 5.0,
    grade: 9.8,
    classAverage: 7.4,
    status: 'Avaliado',
    notes: 'Destaque de desempenho na turma com nota máxima nas questões discursivas.',
  },
  {
    id: 'ass-4',
    childId: 'laura',
    subject: 'Redação & Literatura',
    title: 'Ensaio Crítico: O Quinze e o Modernismo',
    type: 'Trabalho',
    date: '02 de Outubro',
    weight: 3.0,
    status: 'Agendado',
    notes: 'Entrega impressa e apresentação oral de 5 minutos.',
  },
];

export const INITIAL_MEETINGS: PedagogicalMeeting[] = [
  {
    id: 'meet-1',
    childId: 'helena',
    date: '10 de Setembro de 2026',
    teacherOrCoordinator: 'Profª. Camila Rodrigues & Coord. Alice',
    topics: ['Socialização em grupo', 'Foco na leitura autônoma', 'Expressão artística'],
    feedbacks: 'Helena é extremamente solícita com os colegas. Tem demonstrado liderança positiva nas rodas de conversa e uma curiosidade aguçada por livros.',
    actionPoints: [
      'Incentivar a leitura de livros com capítulos curtos em casa.',
      'Reforçar o uso de relógio para ajudar na gestão do tempo das lições.',
    ],
  },
  {
    id: 'meet-2',
    childId: 'laura',
    date: '05 de Setembro de 2026',
    teacherOrCoordinator: 'Prof. Marcos Vinícius (Tutor da Turma)',
    topics: ['Desempenho na Olimpíada de Matemática', 'Integração no Grêmio Estudantil'],
    feedbacks: 'Laura apresenta maturidade acima da média e dedicação exemplar aos estudos e atividades de robótica.',
    actionPoints: ['Apoiar na preparação para a 2ª fase da OBMEP.'],
  },
];

export const INITIAL_CIRCULARS: SchoolCircular[] = [
  {
    id: 'circ-1',
    childId: 'helena',
    title: 'Comunicado nº 18: Feira Literária e Semana da Criança',
    category: 'Circular',
    date: '12/Set/2026',
    description: 'Programação oficial da Semana Literária, autores convidados e oficinas infantis.',
    fileSize: '1.4 MB',
  },
  {
    id: 'circ-2',
    childId: 'laura',
    title: 'Regulamento da Mostra de Ciências e Robótica 2026',
    category: 'Circular',
    date: '08/Set/2026',
    description: 'Normas de segurança e critérios de avaliação dos protótipos de robótica.',
    fileSize: '2.8 MB',
  },
];

export const INITIAL_ACTIVITIES: ExtracurricularActivity[] = [
  // Helena
  {
    id: 'act-1',
    childId: 'helena',
    title: 'Ballet Clássico Infantil',
    category: 'Artes',
    daysOfWeek: ['Terça', 'Quinta'],
    startTime: '15:00',
    endTime: '16:00',
    instructorName: 'Profª. Laura Meirelles',
    instructorContact: '(11) 97766-5544',
    institution: 'Academia Corpo & Movimento',
    address: 'Alameda dos Ipês, 450 - Jardins',
    equipmentChecklist: ['Collant rosa bebê', 'Sapatilhas de meia-ponta', 'Redinha de coque'],
    badgeColor: 'badge-peach',
  },
  // Mateo
  {
    id: 'act-2',
    childId: 'mateo',
    title: 'Natação Infantil & Psicomotricidade Aquática',
    category: 'Esporte',
    daysOfWeek: ['Segunda', 'Quarta'],
    startTime: '16:30',
    endTime: '17:15',
    instructorName: 'Tio Rodrigo',
    instructorContact: '(11) 96655-4433',
    institution: 'Escola de Natação Tubarãozinho',
    address: 'Rua das Palmeiras, 120',
    equipmentChecklist: ['Sunga térmica', 'Óculos de natação', 'Touca de silicone', 'Roupão felpudo'],
    badgeColor: 'badge-sage',
  },
  // Laura
  {
    id: 'act-3',
    childId: 'laura',
    title: 'Robótica Educacional & Programação Arduino',
    category: 'Artes',
    daysOfWeek: ['Quarta', 'Sexta'],
    startTime: '14:30',
    endTime: '16:00',
    instructorName: 'Prof. Felipe Toledo',
    instructorContact: '(11) 95544-3322',
    institution: 'MakerSpace Teen',
    address: 'Av. Paulista, 1800 - 4º andar',
    equipmentChecklist: ['Kit Arduino Uno', 'Notebook e carregador', 'Caderno de prototipagem'],
    badgeColor: 'badge-terracotta',
  },
  // Lucas
  {
    id: 'act-4',
    childId: 'lucas',
    title: 'Musicalização para Primeira Infância & Ritmos',
    category: 'Música',
    daysOfWeek: ['Sábado'],
    startTime: '10:00',
    endTime: '10:45',
    instructorName: 'Tia Clarissa',
    instructorContact: '(11) 94433-2211',
    institution: 'Espaço Som & Afeto',
    address: 'Rua Harmonia, 88 - Vila Madalena',
    equipmentChecklist: ['Chocalhos de madeira', 'Manta confortável', 'Garrafinha de água'],
    badgeColor: 'badge-amber',
  },
];

export const INITIAL_SOCIAL_EVENTS: SocialEvent[] = [
  {
    id: 'evt-1',
    childId: 'helena',
    title: 'Aniversário de 7 Anos da Sofia (Amiga da Escola)',
    eventType: 'Aniversário',
    date: '21 de Setembro (Sábado)',
    time: '15:30',
    location: 'Buffet Estrela Mágica - Rua dos Pinheiros, 700',
    giftSuggestion: 'Livro interativo de artes ou kit de miçangas',
    confirmed: true,
    notes: 'Avisar os pais sobre a alergia grave a amendoim de Helena.',
  },
  {
    id: 'evt-2',
    childId: 'laura',
    title: 'Torneio Intercolegial de Vôlei Sub-13',
    eventType: 'Apresentação',
    date: '27 de Setembro (Sexta)',
    time: '14:00',
    location: 'Ginásio Poliesportivo do Colégio São Luís',
    confirmed: true,
    notes: 'Levar uniforme reserva azul marinho e joelheiras.',
  },
];

export const INITIAL_MEDICATIONS: Medication[] = [
  // Helena
  {
    id: 'med-1',
    childId: 'helena',
    name: 'Amoxicilina + Clavulanato 250mg/5ml',
    dosage: '5.0 ml',
    intervalHours: 8,
    startDate: '16/09/2026',
    endDate: '23/09/2026',
    isActive: true,
    instructions: 'Ministrar com um pouco de alimento para evitar desconforto gástrico. Agitar antes de usar.',
    nextDoseTime: '16:00',
    reminderActive: true,
  },
  {
    id: 'med-2',
    childId: 'helena',
    name: 'Loratadina 5mg/5ml (Uso em Crises Alérgicas)',
    dosage: '5.0 ml',
    intervalHours: 24,
    startDate: '01/01/2026',
    endDate: '31/12/2026',
    isActive: true,
    instructions: 'Uso se houver prurido ou rinite alérgica moderada.',
    nextDoseTime: '20:00',
    reminderActive: false,
  },
  // Mateo
  {
    id: 'med-3',
    childId: 'mateo',
    name: 'Dipirona Gotas 500mg/ml (SOS Febre > 37.8°C)',
    dosage: '14 gotas',
    intervalHours: 6,
    startDate: '01/01/2026',
    endDate: '31/12/2026',
    isActive: true,
    instructions: 'Uso apenas se febre confirmada com termômetro.',
    nextDoseTime: 'Conforme necessidade',
    reminderActive: false,
  },
  // Laura
  {
    id: 'med-4',
    childId: 'laura',
    name: 'Desloratadina 5mg Comprimido',
    dosage: '1 comprimido',
    intervalHours: 24,
    startDate: '10/09/2026',
    endDate: '10/10/2026',
    isActive: true,
    instructions: 'Tomar à noite antes de dormir durante a primavera.',
    nextDoseTime: '21:30',
    reminderActive: true,
  },
  // Lucas
  {
    id: 'med-5',
    childId: 'lucas',
    name: 'Vitamina D3 (Addera D3 Gotas)',
    dosage: '2 gotas',
    intervalHours: 24,
    startDate: '01/01/2026',
    endDate: '31/12/2026',
    isActive: true,
    instructions: 'Pingar diretamente na boca pela manhã durante a primeira refeição.',
    nextDoseTime: '08:30',
    reminderActive: true,
  },
];

export const INITIAL_PRESCRIPTIONS: MedicalPrescription[] = [
  {
    id: 'presc-1',
    childId: 'helena',
    title: 'Receita Amoxicilina & Antialérgicos - Amigdalite',
    date: '16/09/2026',
    doctorName: 'Dra. Beatriz Albuquerque',
    doctorCrm: 'CRM 142.890-SP',
    clinic: 'Hospital Sabará & Consultório Pediátrico',
    medicationsSummary: 'Amoxicilina 250mg (8/8h por 7 dias) + Dipirona 18 gotas se dor',
    dosageInstructions: 'Completar o ciclo de 7 dias rigorosamente mesmo após cessar febre.',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    notes: 'Prescrição digital carimbada e sincronizada com o cofre de documentos.',
    syncedToVault: true,
  },
  {
    id: 'presc-2',
    childId: 'laura',
    title: 'Receita Oftalmológica - Óculos de Descanso',
    date: '10/08/2026',
    doctorName: 'Dr. Paulo Siqueira (Oftalmopediatra)',
    doctorCrm: 'CRM 98.412-SP',
    clinic: 'Instituto de Olhos Paulistano',
    medicationsSummary: 'Lentes com filtro de luz azul (OD: -0.50 cil / OE: -0.50 cil)',
    dosageInstructions: 'Uso durante leitura, telas de computador e estudos.',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80',
    notes: 'Retorno anual para reavaliação de refração.',
    syncedToVault: true,
  },
  {
    id: 'presc-3',
    childId: 'lucas',
    title: 'Protocolo de Cuidados da Pele & Vitamina D3',
    date: '02/03/2026',
    doctorName: 'Dr. Fernando Vasconcelos',
    doctorCrm: 'CRM 115.430-SP',
    clinic: 'Clínica Pediátrica Primeiros Passos',
    medicationsSummary: 'Addera D3 Gotas (2 gotas/dia) + Hidratante Epidrat Calm 2x/dia',
    dosageInstructions: 'Hidratar a pele logo após o banho morno com a pele úmida.',
    imageUrl: 'https://images.unsplash.com/photo-1583912267670-6575ad472688?w=600&auto=format&fit=crop&q=80',
    notes: 'Excelente resposta ao hidratante.',
    syncedToVault: true,
  },
];

export const INITIAL_MED_LOGS: MedicationLog[] = [
  {
    id: 'log-1',
    medicationId: 'med-1',
    childId: 'helena',
    medicationName: 'Amoxicilina 250mg/5ml',
    caregiver: 'Mariana (Mãe)',
    administeredAt: 'Hoje às 08:00',
    note: 'Tomou 5ml após o café da manhã. Sem reações adversas.',
  },
  {
    id: 'log-2',
    medicationId: 'med-1',
    childId: 'helena',
    medicationName: 'Amoxicilina 250mg/5ml',
    caregiver: 'Carlos (Pai)',
    administeredAt: 'Ontem às 16:00',
    note: 'Dose da tarde tomada pontualmente com suco de maçã.',
  },
  {
    id: 'log-3',
    medicationId: 'med-5',
    childId: 'lucas',
    medicationName: 'Vitamina D3 Gotas',
    caregiver: 'Mariana (Mãe)',
    administeredAt: 'Hoje às 08:30',
    note: '2 gotas ministradas durante a papinha de frutas.',
  },
];

export const INITIAL_VACCINES: VaccineRecord[] = [
  // Helena
  {
    id: 'vac-1',
    childId: 'helena',
    vaccineName: 'Tríplice Viral (Sarampo, Caxumba, Rubéola)',
    dose: '2ª Dose (Reforço)',
    recommendedAge: '4 a 6 anos',
    applicationDate: '15/07/2024',
    status: 'Aplicada',
    batchLocation: 'Lote 24A99 - UBS Pinheiros',
  },
  {
    id: 'vac-2',
    childId: 'helena',
    vaccineName: 'Febre Amarela',
    dose: 'Dose de Reforço',
    recommendedAge: '4 anos',
    applicationDate: '20/06/2023',
    status: 'Aplicada',
    batchLocation: 'Lote FA-881 - UBS Pinheiros',
  },
  // Laura
  {
    id: 'vac-3',
    childId: 'laura',
    vaccineName: 'HPV Quadrivalente',
    dose: '1ª e 2ª Doses',
    recommendedAge: '9 a 14 anos',
    applicationDate: '12/03/2025',
    status: 'Aplicada',
    batchLocation: 'Lote HPV-492 - Clínica Vacinare',
  },
  {
    id: 'vac-4',
    childId: 'laura',
    vaccineName: 'Meningocócica ACWY',
    dose: 'Reforço Adolescente',
    recommendedAge: '11 a 12 anos',
    applicationDate: '10/08/2025',
    status: 'Aplicada',
    batchLocation: 'Lote MEN-772 - UBS Pinheiros',
  },
  // Mateo
  {
    id: 'vac-5',
    childId: 'mateo',
    vaccineName: 'Poliomielite (VOP)',
    dose: '2º Reforço',
    recommendedAge: '4 anos',
    applicationDate: '25/03/2026',
    status: 'Aplicada',
    batchLocation: 'Lote VOP-331 - UBS Vila Madalena',
  },
  // Lucas
  {
    id: 'vac-6',
    childId: 'lucas',
    vaccineName: 'Varicela (Catapora)',
    dose: '1ª Dose',
    recommendedAge: '15 a 24 meses',
    applicationDate: '05/03/2026',
    status: 'Aplicada',
    batchLocation: 'Lote VAR-201 - UBS Pinheiros',
  },
];

export const INITIAL_APPOINTMENTS: MedicalAppointment[] = [
  {
    id: 'app-1',
    childId: 'helena',
    specialty: 'Pediatria Geral & Alergologia',
    doctorName: 'Dra. Beatriz Albuquerque',
    clinic: 'Consultório Sabará - Jardins',
    date: '25/Out/2026',
    time: '14:30',
    diagnosis: 'Acompanhamento preventivo anual e checagem de imunoglobulinas.',
    prescriptions: ['Painel de IGE específico', 'Receita de caneta de adrenalina autoinjetável'],
    returnDate: 'Outubro de 2027',
  },
  {
    id: 'app-2',
    childId: 'laura',
    specialty: 'Hebiatria (Saúde do Adolescente)',
    doctorName: 'Dra. Mariana Gontijo',
    clinic: 'Clínica Adolescer - Sírio-Libanês',
    date: '18/Nov/2026',
    time: '16:00',
    diagnosis: 'Consulta de rotina do estirão puberal e postura escoliótica.',
    prescriptions: ['Hemograma completo', 'Ferritina', 'Vitamina D'],
    returnDate: 'Maio de 2027',
  },
  {
    id: 'app-3',
    childId: 'lucas',
    specialty: 'Puericultura (2 Anos)',
    doctorName: 'Dr. Fernando Vasconcelos',
    clinic: 'Consultório Primeiros Passos',
    date: '15/Out/2026',
    time: '10:00',
    diagnosis: 'Avaliação do marco motor, vocabulário e curva pôndero-estatural.',
    prescriptions: ['Manutenção de Vitamina D3'],
    returnDate: 'Abril de 2027',
  },
];

export const INITIAL_GROWTH: GrowthRecord[] = [
  // Helena
  {
    id: 'gr-1',
    childId: 'helena',
    date: '15/Jun/2026',
    ageMonths: 84,
    ageDisplay: '7 anos',
    heightCm: 122.5,
    weightKg: 22.8,
    percentileText: 'Percentil 65 (Estatura e peso ideais)',
    notes: 'Crescimento harmonioso no canal P60-P70.',
  },
  // Mateo
  {
    id: 'gr-2',
    childId: 'mateo',
    date: '22/Mar/2026',
    ageMonths: 48,
    ageDisplay: '4 anos',
    heightCm: 104.0,
    weightKg: 16.5,
    percentileText: 'Percentil 55 (Curva saudável padrão OMS)',
    notes: 'Ganho consistente de peso e massa magra.',
  },
  // Laura
  {
    id: 'gr-3',
    childId: 'laura',
    date: '10/Ago/2026',
    ageMonths: 144,
    ageDisplay: '12 anos',
    heightCm: 154.0,
    weightKg: 43.5,
    percentileText: 'Percentil 75 (Início de estirão puberal)',
    notes: 'Postura excelente e acompanhamento da coluna regular.',
  },
  // Lucas
  {
    id: 'gr-4',
    childId: 'lucas',
    date: '18/Fev/2026',
    ageMonths: 24,
    ageDisplay: '2 anos',
    heightCm: 87.5,
    weightKg: 12.4,
    headCircumferenceCm: 48.2,
    percentileText: 'Percentil 60 (Desenvolvimento excelente)',
    notes: 'Perímetro cefálico e marcos motores 100% preservados.',
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: 'not-1',
    childId: 'helena',
    title: 'Recado da Professora de Artes: Caixa de Sapato',
    content: 'Levar 1 caixa de sapato vazia e 2 rolos de papel toalha até terça-feira para a maquete da cidade sustentável.',
    tags: ['Escola', 'Material', 'Urgente'],
    isPinned: true,
    createdAt: '18/Set/2026',
    tagColorClass: 'bg-warm-peach-light text-warm-terracotta border-border-peach',
  },
  {
    id: 'not-2',
    title: 'Lista de Compras da Farmácia do Mês',
    content: '• Protetor solar Kids FPS 50\n• Repelente infantil Icaridina\n• Algodão e soro fisiológico\n• Termômetro digital reserva',
    tags: ['Família', 'Farmácia', 'Rotina'],
    isPinned: true,
    createdAt: '17/Set/2026',
    tagColorClass: 'bg-warm-sage-light text-warm-sage-dark border-warm-sage/40',
  },
  {
    id: 'not-3',
    childId: 'laura',
    title: 'Inscrição na Feira de Ciências & Ideias',
    content: 'O grupo da Laura vai apresentar o protótipo de irrigador automatizado com sensor de umidade de solo.',
    tags: ['Robótica', 'Projetos'],
    isPinned: false,
    createdAt: '15/Set/2026',
    tagColorClass: 'bg-warm-peach-light text-warm-terracotta border-border-peach',
  },
];

export const INITIAL_TASKS: Task[] = [
  // Helena
  {
    id: 'tsk-1',
    childId: 'helena',
    title: 'Arrumar a mochila com o estojo e livro de histórias',
    category: 'child',
    priority: 'alta',
    dueTime: '20:00',
    completed: true,
    rewardStars: 2,
  },
  {
    id: 'tsk-2',
    childId: 'helena',
    title: 'Praticar 15 minutos de leitura em voz alta',
    category: 'child',
    priority: 'media',
    dueTime: '19:30',
    completed: false,
    rewardStars: 3,
  },
  // Laura
  {
    id: 'tsk-3',
    childId: 'laura',
    title: 'Finalizar lista de 10 exercícios de álgebra',
    category: 'child',
    priority: 'alta',
    dueTime: '18:00',
    completed: true,
    rewardStars: 2,
  },
  // Mateo
  {
    id: 'tsk-4',
    childId: 'mateo',
    title: 'Guardar os blocos de montar no baú de brinquedos',
    category: 'child',
    priority: 'baixa',
    dueTime: '19:00',
    completed: true,
    rewardStars: 1,
  },
];

export const INITIAL_MEMORIES: MemoryMoment[] = [
  {
    id: 'mem-1',
    childId: 'helena',
    title: 'Apresentação de Primavera no Ballet: O Lago das Flores',
    date: '14 de Setembro de 2026',
    category: 'Artes',
    narrative: 'Helena dançou radiante com as coleguinhas. Foi o primeiro solo curto dela e a emoção de todos os avós na plateia foi inesquecível!',
    imageUrl: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=600&auto=format&fit=crop&q=80',
    location: 'Teatro Municipal de São Paulo',
  },
  {
    id: 'mem-2',
    childId: 'mateo',
    title: 'Primeiro Mergulho sem Boias nos Braços',
    date: '02 de Setembro de 2026',
    category: 'Conquistas',
    narrative: 'Mateo pegou o barquinho de brinquedo no fundo da piscina infantil com um sorriso imenso de vitória.',
    imageUrl: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&auto=format&fit=crop&q=80',
    location: 'Clube dos Pinheiros',
  },
  {
    id: 'mem-3',
    childId: 'laura',
    title: 'Medalha de Prata na Olimpíada de Robótica',
    date: '20 de Agosto de 2026',
    category: 'Conquistas',
    narrative: 'O robô seguidor de linha construído pela Laura e seu time completou a pista em tempo recorde!',
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&auto=format&fit=crop&q=80',
    location: 'Centro de Convenções Anhembi',
  },
  {
    id: 'mem-4',
    childId: 'lucas',
    title: 'Festa de 2 Anos do Lucas no Quintal',
    date: '18 de Fevereiro de 2026',
    category: 'Família',
    narrative: 'Bolo de banana e aveia, primos correndo na grama e muitas risadas com bolhas de sabão.',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop&q=80',
    location: 'Casa da Vovó Luísa',
  },
];

export const INITIAL_MILESTONES: DevelopmentMilestone[] = [
  {
    id: 'mil-1',
    childId: 'helena',
    title: 'Leitura Fluida do Primeiro Livro sem Ajuda',
    category: 'Linguagem',
    ageAchieved: '6 anos e 8 meses',
    dateAchieved: 'Março/2026',
    description: 'Leu o livro "A Menina que Amava Estrelas" do início ao fim com entonação correta.',
  },
  {
    id: 'mil-2',
    childId: 'lucas',
    title: 'Primeiras Frases Completas ("Papai me dá bola")',
    category: 'Linguagem',
    ageAchieved: '1 ano e 11 meses',
    dateAchieved: 'Janeiro/2026',
    description: 'Combinação clara de sujeito, verbo e objeto nas conversas diárias.',
  },
  {
    id: 'mil-3',
    childId: 'mateo',
    title: 'Andar de Bicicleta sem Rodinhas de Apoio',
    category: 'Motor',
    ageAchieved: '3 anos e 10 meses',
    dateAchieved: 'Janeiro/2026',
    description: 'Equilíbrio perfeito na ciclovia do parque em menos de dois finais de semana de treino.',
  },
];

export const INITIAL_ARTWORKS: ArtworkItem[] = [
  {
    id: 'art-1',
    childId: 'helena',
    title: 'O Jardim Encantado dos Pássaros Azuis',
    date: '08/Set/2026',
    technique: 'Giz de cera pastel e colagem de folhas secas',
    description: 'Trabalho de artes plásticas selecionado para o mural da escola.',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'art-2',
    childId: 'mateo',
    title: 'O Foguete que foi até a Lua de Queijo',
    date: '01/Set/2026',
    technique: 'Tinta guache atóxica sobre papel canson',
    description: 'Pintura livre feita com os dedinhos após a historinha do astronauta.',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'art-3',
    childId: 'laura',
    title: 'Aquarela Urbana: Fachadas de São Paulo',
    date: '15/Jul/2026',
    technique: 'Aquarela fina sobre papel algodão 300g',
    description: 'Estudo de luz e sombra nas janelas antigas do centro histórico.',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_DOCUMENTS: DocumentFile[] = [
  {
    id: 'doc-1',
    childId: 'helena',
    name: 'Certidao_Nascimento_Helena_Silva.pdf',
    folderCategory: 'Oficiais',
    fileType: 'pdf',
    size: '2.4 MB',
    uploadDate: '10/Jan/2026',
    description: 'Certidão de nascimento registrada no 14º Cartório de Registro Civil de SP.',
  },
  {
    id: 'doc-2',
    childId: 'helena',
    name: 'Contrato_Escolar_Santa_Teresa_2026.pdf',
    folderCategory: 'Educação',
    fileType: 'pdf',
    size: '4.8 MB',
    uploadDate: '15/Fev/2026',
    description: 'Contrato de prestação de serviços educacionais e autorização de saídas pedagógicas.',
  },
  {
    id: 'doc-3',
    childId: 'laura',
    name: 'Boletim_Escolar_2_Bimestre_Laura.pdf',
    folderCategory: 'Educação',
    fileType: 'pdf',
    size: '1.2 MB',
    uploadDate: '10/Jul/2026',
    description: 'Boletim acadêmico oficial com média global 9.4 e 100% de presença.',
  },
  {
    id: 'doc-4',
    childId: 'lucas',
    name: 'Carteira_Vacinacao_Digital_Lucas.pdf',
    folderCategory: 'Saúde',
    fileType: 'pdf',
    size: '3.1 MB',
    uploadDate: '01/Mar/2026',
    description: 'Histórico completo de vacinas do Programa Nacional de Imunizações (PNI).',
  },
];
